# Generated by Django 3.2.9 on 2021-12-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPerfiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
