# Generated by Django 3.2.9 on 2021-12-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRegistro', '0004_suscriptor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=15)),
                ('profesion', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=10)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='suscriptor',
            name='profesion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='esAdmin',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='fechaNacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(),
        ),
    ]
