# Generated by Django 3.2.9 on 2021-12-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRegistro', '0005_auto_20211216_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redactor',
            old_name='nombreUsuario',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='profesion',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='esAdmin',
            field=models.BooleanField(),
        ),
    ]
